<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/grpc.proto

namespace GPBMetadata\Proto;

class Grpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae010a1070726f746f2f677270632e70726f746f12046772706322230a06486955736572120c0a046e616d65180120012809120b0a0373657818022001280522360a0748695265706c79120f0a076d657373616765180120012809121a0a047573657218022001280b320c2e677270632e486955736572322f0a02686912290a0873617948656c6c6f120c2e677270632e4869557365721a0d2e677270632e48695265706c792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

